# SPDX-FileCopyrightText: 2025 Menno van der Graaf <mennovandergraaf@hotmail.com>
# SPDX-License-Identifier: MIT
version = 1

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "2025 Menno van der Graaf <mennovandergraaf@hotmail.com>"
SPDX-License-Identifier = "MIT"
