name: CI Build

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build for web
        run: wasm-pack build --target web
